# Generated by Django 5.0.2 on 2024-03-11 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='celebrationparticipants',
            old_name='celebrationid',
            new_name='celebration',
        ),
    ]
