# Generated by Django 5.0.2 on 2024-03-21 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_leave_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='isapproved',
        ),
    ]
